version: '3'

services:
  nodeservice:
    container_name: ${NODE_SERVICE}
    build: ./${NODE_SERVICE}
    ports:
      - "3004:3004"
    networks:
      - news_tracker
    volumes:
      - ./${NODE_SERVICE}:/app
      - /app/node_modules
      - /home/${USER}/.cache/puppeteer:/app/.cache/puppeteer:ro

    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_CACHE_DIR=/app/.cache/puppeteer
      - PUPPETEER_EXECUTABLE_PATH=/app/.cache/puppeteer/chrome/linux-139.0.7258.66/chrome-linux64/chrome
      - MONGO_URI=${MONGO_URI}
      - AWSS3REGION=${AWSS3REGION}
      - AWSACCESSKEY=${AWSACCESSKEY}
      - AWSSECRETACCESSKEY=${AWSSECRETACCESSKEY}

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  pythonservice:
    container_name: ${PYTHON_SERVICE}
    build: ./${PYTHON_SERVICE}
    ports:
      - "3005:3005"
    networks:
      - news_tracker
    volumes:
      - ./${PYTHON_SERVICE}:/app
      - ./files:/app/api/files
    environment:
      - PORT=3005
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_TRACING=${LANGSMITH_ENDPOINT}
      - LANGSMITH_TRACING=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_PROJECT}
      - LANGSMITH_TRACING=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWSS3REGION=${AWSS3REGION}
      - AWS_ACCESS_KEY_ID=${AWSACCESSKEY}
      - AWS_SECRET_ACCESS_KEY=${AWSSECRETACCESSKEY}
    restart: always

networks:
    news_tracker:
      external: true

volumes:
    mongo_data:

